---
- hosts: www

  vars:
    - root_dir: ..


  pre_tasks:
    - debug: msg="Pre tasks section"

  roles:
     - {
         role: "sa-deepgraph"
       }


  tasks:

    - debug: msg="Tasks section"

